### ISSUE TITLE
Can't upload file 

### ISSUE THREAD

**Issue by Chauloe1808** [CYS4srl/CYS4-SensitiveDiscoverer#1]
Hi,
I downloaded the default regex and re-uploaded it but it didn't work. Can you show the specific format to upload?

**Comment by checkm50** [comment]
Hi,
I have observed the same behavior. 
Could you please let us know if we are doing something wrong?

**Comment by LorenzoCoppi-cys4** [comment]
Hi, thanks for the feedback!

This fix will be in the next release. The README will also be updated with information on how to format the CSV file for importing it.
