### ISSUE TITLE
Suggestion : Can you add choice to ananlyse Logger history ? 

### ISSUE THREAD

**Issue by ayadim** [CYS4srl/CYS4-SensitiveDiscoverer#3]
Hi,
thank you for this great extension I really loved it,

my suggestion Is very clear since the extension target the HTTP history why you do not add a bottom to analyze the logger history? 
I really want to see this in new updates.

Regards

**Comment by LorenzoCoppi-cys4** [comment]
Thanks for the feedback.

We are looking forward to implementing that feature in a future release. Unfortunately, as of now, a timeline has not been defined.

**Comment by ayadim** [comment]
hi,
thank you for responding, am waiting to see new features.
regards

**Comment by beryxz** [comment]
The BurpSuite's information accessible through the API only provides a method for retrieving the proxy history. It doesn't seems possible to obtain the logger history.

For reference, look for the `Interface IBurpExtenderCallbacks` inside the Javadoc API URL: https://portswigger.net/burp/extender/api/index.html
