### ISSUE TITLE
Problem with Import functionnality 

### ISSUE THREAD

**Issue by ayadim** [CYS4srl/CYS4-SensitiveDiscoverer#6]
Hi,
I hope you are well, so I have an issue importing the saved REGEX list.
first I export the regex list and save it in a CSV extension (sensitiveDiscoverer.csv).
then when I close the burp or even I clear the list and then import my saved list (sensitiveDiscoverer.csv) it is not loaded !!!

regards

**Comment by LorenzoCoppi-cys4** [comment]
Duplicate of #1 , it will be fixed in the next release v2.1.0

**Comment by ayadim** [comment]
ok thank you
